### ISSUE TITLE
Unable to start program

### ISSUE THREAD

**Issue by XerOracle** [entynetproject/ehtools#11]
After the installation is complete, enter ehtools prompt no command found, how can I solve it? Thank you!

**Comment by enty8080** [comment]
Yesterday we are working on the new Ehools Framework Structure, just run uninstall.sh and after this reclone ehtools and install it again.

**Comment by XerOracle** [comment]
> 昨天，我们正在开发新的Ehools框架结构，只需运行uninstall.sh，然后重新克隆ehtools并重新安装即可。

Thank you！
