### ISSUE TITLE
Entering ehtools still prompts command not found

### ISSUE THREAD

**Issue by XerOracle** [entynetproject/ehtools#12]
I re-cloned and installed after uninstalling according to your method, but the problem still exists, and the command is still not found. I see that the install.sh file has not been updated on the homepage, so I think the problem is caused by the file not being updated. Re-cloning the installation was not resolved. Please help me, thanks!

**Comment by enty8080** [comment]
What OS do you use?

**Comment by XerOracle** [comment]
> 您使用什么操作系统？


I'm using Ubuntu.

**Comment by enty8080** [comment]
Sorry, ehtools only supports Kali and ParrotOS
