### ISSUE TITLE
No uninstall.sh

### ISSUE THREAD

**Issue by machutmayen** [entynetproject/ehtools#13]
I am trying to uninstall ehtools, but there's no uninstall.sh

**Comment by enty8080** [comment]
What?? There is an uninstall.sh, maybe you remove it.

**Comment by enty8080** [comment]
![EB31FC4B-845B-4192-8165-F2127B9A14AE](https://user-images.githubusercontent.com/54115104/80962758-51249c80-8e16-11ea-9178-4c2d9cd8d9ef.jpeg)
![498E7077-53F7-4E85-83DB-3EF6F6E333C8](https://user-images.githubusercontent.com/54115104/80962761-5255c980-8e16-11ea-8758-adf5255b48cb.jpeg)
