### ISSUE TITLE
upgrade from Lite to Pro

### ISSUE THREAD

**Issue by sh1va73** [entynetproject/ehtools#8]
Can I upgrade from Lite to Pro?
I tried to uninstall Lite version but uninstall give me an error

[*] Failed to open session for uninstall.sh!

Also i tried to remove the ehtools folder manually and reinstalled as pro , but when I open the program its still the Lite version.

**Comment by enty8080** [comment]
Run install.sh
And select pro version, after this enter your activation key

**Comment by sh1va73** [comment]
I did install.sh but I installed Lite. 
Now I like the tool and I want to change to Pro but get error. [*] Failed to open session for uninstall.sh!

**Comment by sh1va73** [comment]
I tried again :Run install.sh And select pro version, after this enter  activation key
After install: Plan | Ehtools Framework : LITE
I cant install the Pro version it seems because LITE is already installed.

**Comment by enty8080** [comment]
So, you can execute this:
chmod +x /root/ehtools/etc/lite/uninstall.sh
/root/ehtools/etc/lite/uninstall.sh --force-uninstall

**Comment by sh1va73** [comment]
I tried that but I get this error with force-uninstall:[*] Failed to open session for uninstall.sh!

**Comment by enty8080** [comment]
Ok, run this (in one line!!!):
rm -f /root/ehtools/uninstall.sh && curl https://raw.githubusercontent.com/entynetproject/ehtools/master/etc/lite/uninstall.sh >> /root/ehtools/uninstall.sh

**Comment by enty8080** [comment]
And after this execute uninstall.sh with command:
chmod +x /root/ehtools/uninstall.sh && /root/ehtools/uninstall.sh

**Comment by sh1va73** [comment]
Thanks for your time and help. Almost successful; but there is a /etc/ folder inside with a lock. 
I can't delete that folder. Its inside ehtools. I am root but I get an error I can't delete the folder because I don't have the rights.

**Comment by sh1va73** [comment]
Now uninstall was successful, thanks for your help.
I reinstalled ehtools with activation code from above but it still says: Plan | Ehtools Framework : LITE

**Comment by enty8080** [comment]
It's so strange, you should to uninstall it again and you should to git clone another and just copy the activation key and enter itto the (activation_key)> field. I checked Ehtools Framework on my computer and it works very well.
